# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Test RESTEasy

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '.gitignore'
      - ".github/workflows/manual-*.yml"
      - ".mvn/**"
      - "docbook/**"
      - "distribution/**"
      - "CODEOWNERS"
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.adoc"
      - "dco.txt"
      - "LICENSE"
      - "mvnw"
      - "mvnw.cmd"
      - "README.md"
      - "SECURITY.md"
      - "**/README.MD"
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '.gitignore'
      - ".github/workflows/manual-*.yml"
      - ".mvn/**"
      - "docbook/**"
      - "distribution/**"
      - "CODEOWNERS"
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.adoc"
      - "dco.txt"
      - "LICENSE"
      - "mvnw"
      - "mvnw.cmd"
      - "README.md"
      - "SECURITY.md"
      - "**/README.MD"

# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:

    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest ]
        java: ['17']
        # wildfly-version: ${{ env.WILDFLY_VERSIONS }}

    steps:
      - name: Testing
        run:  |
          env
          echo ${{ env.WILDFLY_VERSIONS }}
